name: arm64-linux-docker
on: push
jobs:
  build-on-aarch64:
    runs-on: ubuntu-latest
    name: ci (arm64)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build in arm64 container
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: aarch64
          distro: ubuntu20.04
          # Install deps into the container. With the token, the container will be cached
          # The image is cached publically like a package
          githubToken: ${{ github.token }}
          install: |
            apt-get update -y
            apt-get upgrade -y
            apt-get install git clang gcc -y
          run: |
            git --version
            g++ --version
            clang++ --version
            ls
