name: arm64-linux-docker
on: push
jobs:
  build-on-aarch64:
    runs-on: ubuntu-latest
    name: ci (arm64)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build in arm64 container
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: aarch64
          distro: alpine_latest
          githubToken: ${{ github.token }}
          install: |
            #apt-get update -qy
            #apt-get upgrade -qy
            #apt-get install -qy git clang g++ lld
            apk update
            apk upgrade
            apk add --no-cache g++ clang clang-dev lld
            #apk add lld
            #apk add musl-dev
          run: |
            ls -l
            clang++ *.cpp -o helloworld -std=c++20
            ls -l
