name: arm64-linux-docker
on: push
jobs:
  arm64-linux-docker:
    runs-on: ubuntu-latest
    container:
      image: arm64v8/alpine:latest
    steps:
    - name: Greeting
      run: |
        cat /etc/alpine-release
