name: Build Linux macOS Windows
on:
  push:
    branches: [ main ]
    tags:
      - "*"
jobs:
  build-linux:
    name: 'Build Linux'
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build source
      run: |
        sudo apt-get -y -q update && sudo apt-get -y -q upgrade
        sudo apt-get -y -q install g++-10-i686-linux-gnu
        sudo apt-get -y -q install g++-10-arm-linux-gnueabihf
        sudo apt-get -y -q install g++-10-aarch64-linux-gnu
        #
        ls -l /usr/bin | grep linux-gnu
        #
        i686-linux-gnu-g++-10 helloworld.cpp -o helloworld-i686 -std=c++20 -O2
        i686-linux-gnu-strip -s helloworld-i686
        file helloworld-i686
        #
        x86_64-linux-gnu-g++-10 helloworld.cpp -o helloworld-amd64 -std=c++20 -O2
        x86_64-linux-gnu-strip -s helloworld-amd64
        file helloworld-amd64
        #
        arm-linux-gnu-g++-10 helloworld.cpp -o helloworld-arm -std=c++20 -O2
        arm-linux-gnu-strip -s helloworld-arm
        file helloworld-arm
        #
        aarch64-linux-gnu-g++-10 helloworld.cpp -o helloworld-arm64 -std=c++20 -O2
        aarch64-linux-gnu-strip -s helloworld-arm64
        file helloworld-arm64
      shell: bash
    - name: Upload artifacs
      uses: actions/upload-artifact@v2
      with:
        name: 'ubuntu-latest'
        path: |
          README.md
          helloworld-i686
          helloworld-amd64
          helloworld-arm
          helloworld-arm64
  build-windows:
    name: 'Build Windows'
    runs-on: 'windows-latest'
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build source
      run: |
        clang++ helloworld.cpp -o helloworld.exe -std=c++20 -O2
      shell: bash
    - name: Upload artifacs
      uses: actions/upload-artifact@v2
      with:
        name: 'windows-latest'
        path: |
          README.md
          helloworld.exe
  build-macos:
    name: 'Build macOS'
    runs-on: 'macos-latest'
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build source
      run: |
        g++ helloworld.cpp -o helloworld -std=c++20 -O2
        strip -x helloworld
        file helloworld
      shell: bash
    - name: Upload artifacs
      uses: actions/upload-artifact@v2
      with:
        name: 'macos-latest'
        path: |
          README.md
          helloworld
  release-linux:
    if: contains(github.ref, '/tags/')
    name: 'Release ubuntu-latest'
    runs-on: 'ubuntu-latest'
    needs: [build-linux]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Package artifacts
        run: |
          tag=${{ github.event.ref }}
          tag=${tag#"refs/tags/"}
          cp ubuntu-latest/README.md README.md
          #
          cp ubuntu-latest/helloworld-i686 helloworld
          chmod +x helloworld
          tar -zcvf helloworld-${tag}-linux-i686.tar.gz helloworld README.md
          #
          cp ubuntu-latest/helloworld-amd64 helloworld
          chmod +x helloworld
          tar -zcvf helloworld-${tag}-linux-amd64.tar.gz helloworld README.md
          #
          cp ubuntu-latest/helloworld-arm helloworld
          chmod +x helloworld
          tar -zcvf helloworld-${tag}-linux-arm.tar.gz helloworld README.md
          #
          cp ubuntu-latest/helloworld-arm64 helloworld
          chmod +x helloworld
          tar -zcvf helloworld-${tag}-linux-arm64.tar.gz helloworld README.md
        shell: bash
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            helloworld-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-macos:
    if: contains(github.ref, '/tags/')
    name: 'Release macos-latest'
    runs-on: 'macos-latest'
    needs: [build-macos]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Package artifacts
        run: |
          tag=${{ github.event.ref }}
          tag=${tag#"refs/tags/"}
          cp macos-latest/README.md README.md
          cp macos-latest/helloworld helloworld
          chmod +x helloworld
          tar -zcvf helloworld-${tag}-darwin-amd64.tar.gz helloworld README.md
        shell: bash
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            helloworld-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-windows:
    if: contains(github.ref, '/tags/')
    name: 'Release windows-latest'
    runs-on: 'windows-latest'
    needs: [build-windows]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Package artifacts
        run: |
          tag=${{ github.event.ref }}
          tag=${tag#"refs/tags/"}
          cp windows-latest/README.md README.md
          cp windows-latest/helloworld.exe helloworld.exe
          7z a -tzip helloworld-${tag}-windows-amd64.zip helloworld.exe README.md
        shell: bash
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            helloworld-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
