name: Build
on:
  push:
    branches: [ main ]
    tags:
      - "*"
jobs:
  build-linux-amd64-arm64:
    name: 'Build Linux-amd64 and arm64'
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build source
      run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
          sudo apt-get -y -qq install g++-aarch64-linux-gnu
          #
          x86_64-linux-gnu-g++ --version
          x86_64-linux-gnu-g++ -v --help 2> /dev/null | sed -n '/^ *-std=\([^<][^ ]\+\).*/ {s//\1/p}'
          aarch64-linux-gnu-g++ --version
          aarch64-linux-gnu-g++ -v --help 2> /dev/null | sed -n '/^ *-std=\([^<][^ ]\+\).*/ {s//\1/p}'
          #
          x86_64-linux-gnu-g++ helloworld.cpp -o helloworld-amd64 -std=c++20 -O2
          x86_64-linux-gnu-strip -s helloworld
          file helloworld-amd64
          #
          aarch64-linux-gnu-g++ helloworld.cpp -o helloworld-arm64 -std=c++20 -O2
          aarch64-linux-gnu-strip -s helloworld-arm64
          file helloworld-arm64
      shell: bash
    - name: Upload artifacs
      uses: actions/upload-artifact@v2
      with:
        name: 'ubuntu-latest'
        path: |
          README.md
          helloworld-amd64
          helloworld-arm64
  release:
    if: contains(github.ref, '/tags/')
    name: 'Release ubuntu-latest'
    runs-on: 'ubuntu-latest'
    needs: [build-linux-amd64-arm64]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Package artifacts
        run: |
          ls -al
          tag=${{ github.event.ref }}
          tag=${tag#"refs/tags/"}
            cp ubuntu-latest/README.md README.md
            cp ubuntu-latest/helloworld-amd64 helloworld
            chmod +x helloworld
            tar -zcvf helloworld-${tag}-linux-amd64.tar.gz helloworld README.md
            cp ubuntu-latest/helloworld-arm64 helloworld
            chmod +x helloworld
            tar -zcvf helloworld-${tag}-linux-arm64.tar.gz helloworld README.md
        shell: bash
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            helloworld-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
