name: C/C++ CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: 'Build: ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build source
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          clang++ helloworld.cpp -o helloworld -std=c++20 -O2
          strip -s helloworld
        elif [ "$RUNNER_OS" == "macOS" ]; then
          clang++ helloworld.cpp -o helloworld -std=c++20 -O2
          strip -x helloworld
        elif [ "$RUNNER_OS" == "Windows" ]; then
          clang-cl helloworld.cpp -o helloworld -std=c++20 -O2
        else
          echo "$RUNNER_OS not supported build"
          exit 1
        fi
      shell: bash
    - name: Run simple
      run: ./helloworld
    - name: Upload artifacs
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: |
          helloworld
  
  release:
    if: contains(github.ref, '/tags/')
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: 'Release: ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Package artifacts
        run: |
          ls -al
          os="${RUNNER_OS,,}"
          tag=${{ github.event.ref }}
          tag=${tag#"refs/tags/"}
          if [ "$RUNNER_OS" == "Linux" ]; then
            cp ubuntu-latest/helloworld .
            chmod +x helloworld
            tar -zcvf helloworld-${tag}-amd64-${os}.tar.gz helloworld
          elif [ "$RUNNER_OS" == "macOS" ]; then
            cp macos-latest/helloworld .
            chmod +x helloworld
            tar -zcvf helloworld-${tag}-amd64-${os}.tar.gz helloworld
          elif [ "$RUNNER_OS" == "Windows" ]; then
            cp windows-latest/helloworld.exe .
            zip helloworld-${tag}-amd64-${os}.zip helloworld.exe
          else
            echo "$RUNNER_OS not supported release"
            exit 1
          fi
        shell: bash
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            helloworld-*.zip
            helloworld-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
