name: C/C++ CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: 'Build: ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build source
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          clang++ helloworld.cpp -o helloworld -std=c++20 -O2
          strip -s helloworld
        elif [ "$RUNNER_OS" == "macOs" ]; then
          clang++ helloworld.cpp -o helloworld -std=c++20 -O2
          strip -x helloworld
        elif [ "$RUNNER_OS" == "Windows" ]; then
              clang-cl helloworld.cpp -o helloworld -std=c++20 -O2
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash
    - name: Run simple
      run: ./helloworld
    - name: Upload artifacs
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: |
          helloworld
  
  release:
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: 'Release: ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        name: Download artifacts
      - name: List everything
        run: |
          ls -al
      - name: Package artifacts - linux
        run: |
          cp ubuntu-latest/helloworld .
          tag=${{ github.event.ref }}
          tag=${tag#"refs/tags/"}
          tar -zcvf helloworld-${tag}-amd64-linux.tar.gz helloworld
      - name: Package artifacts - macos
        run: |
          cp macos-latest/helloworld .
          tag=${{ github.event.ref }}
          tag=${tag#"refs/tags/"}
          tar -zcvf helloworld-${tag}-amd64-macos.tar.gz helloworld
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            helloworld-*.zip
            helloworld-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
